from result import Error


def test_error():
    print(Error("this is a test"))
